language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - llvm-3.5
      - llvm-3.5-dev
      - libedit-dev
script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.5 . && make && make tests
notifications:
  email:
    recipients:
      - tomh5908@gmail.com
  on_success: never
  on_failure: change
