jobs:
  include:
    - sudo: required
      dist: precise
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-3.2
          - llvm-3.2-dev
          - clang
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.2 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: precise
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-3.3
          - llvm-3.3-dev
          - clang-3.3
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.3 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: trusty
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-3.5
          - llvm-3.5-dev
          - clang-3.5
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.5 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: trusty
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-3.6
          - llvm-3.6-dev
          - clang-3.6
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.6 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: xenial
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-3.8
          - llvm-3.8-dev
          - clang-3.8
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-3.8 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: xenial
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-4.0
          - llvm-4.0-dev
          - clang-4.0
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-4.0 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: xenial
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-5.0
          - llvm-5.0-dev
          - clang-5.0
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-5.0 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: focal
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-6.0
          - llvm-6.0-dev
          - clang-6.0
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-6.0 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: focal
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-7
          - llvm-7-dev
          - clang-7
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-7 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
    - sudo: required
      dist: focal
      language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
          - git
          - llvm-8
          - llvm-8-dev
          - clang-8
          - libedit-dev
      script: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-8 . && make && make tests
      notifications:
        email:
          recipients:
          - tomh5908@gmail.com
        on_success: never
        on_failure: change
